version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - minio
    environment:
      DB_HOST: db
      DB_DATABASE: user
      DB_USERNAME: root
      DB_PASSWORD:
      MINIO_ENDPOINT: minio:9000
      MINIO_KEY: jabran
      MINIO_SECRET: jabran

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: images
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: jabran
      MINIO_ROOT_PASSWORD: jabran

volumes:
  minio_data:
